### ISSUE TITLE
npm install step fails

### ISSUE THREAD

**Issue by getaaron** [circleci/circleci-images#176]
From my `.circleci/config.yml` file:

```yml
  build-and-test-android:
    working_directory: /Users/distiller/project
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
```

When the build runs, the `npm install` step fails:

![image](https://user-images.githubusercontent.com/789577/37849512-3fda0b32-2e95-11e8-89d1-6e7ee349c0cb.png)

From `npm-debug.log`:

```
5444 verbose afterAdd /Users/distiller/.npm/@babel/types/7.0.0-beta.42/package/package.json not in flight; writing
5445 verbose correctMkdir /Users/distiller/.npm correctMkdir not in flight; initializing
5446 verbose afterAdd /Users/distiller/.npm/@babel/types/7.0.0-beta.42/package/package.json written
5447 silly rollbackFailedOptional Starting
5448 silly rollbackFailedOptional Finishing
5449 silly runTopLevelLifecycles Finishing
5450 silly install printInstalled
5451 verbose stack Error: Unsupported URL Type: npm:babylon@^7.0.0-beta
5451 verbose stack     at parseUrl (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:186:13)
5451 verbose stack     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:79:12)
5451 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:12:15)
5451 verbose stack     at childDependencySpecifier (/usr/local/lib/node_modules/npm/lib/install/deps.js:89:3)
5451 verbose stack     at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:425:3)
5451 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:384:5
5451 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
5451 verbose stack     at Array.forEach (native)
5451 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
5451 verbose stack     at Array.forEach (native)
5452 verbose cwd /Users/distiller/ManheimExpress
5453 error Darwin 15.6.0
5454 error argv "/usr/local/Cellar/node/6.9.1/bin/node" "/usr/local/bin/npm" "install"
5455 error node v6.9.1
5456 error npm  v3.10.8
5457 error Unsupported URL Type: npm:babylon@^7.0.0-beta
5458 error If you need help, you may report this error at:
5458 error     <https://github.com/npm/npm/issues>
5459 verbose exit [ 1, true ]
```

Since I'm not running `npm install` I assume this is part of the CircleCI provided image. Any idea why it's failing?

**Comment by iynere** [comment]
hi there, our Android images do not have a `Users/distiller/project` path—that path is specific to our macOS images, I believe... so that's definitely going cause issues for you

not sure why `npm install` is running either, but there was a recent issue with GitHub that caused many config files to not be picked up, which would cause projects to default to running as 1.0 builds with inference, which may explain where `npm install` might come from...

https://status.circleci.com

**Comment by getaaron** [comment]
Thanks @iynere, I think that was the issue. This project is react native so has both iOS and Android. So I guess CircleCI 1 installed the iOS config
