### ISSUE TITLE
recent build-tools (30.0.1 and 30.0.2) not included in android images

### ISSUE THREAD

**Issue by tkazmierczak-tt** [circleci/circleci-images#501]
We recently moved to api-30 image and noticed that the build-tools in version 30.0.1 and 30.0.2 are not included and are downloaded every CI run.

**Comment by felicianotech** [comment]
The work for this was done in this PR that was just merged: https://github.com/circleci/circleci-images/pull/502

This change will hit our production images on Monday along with other Android changes: https://github.com/circleci/circleci-images/issues/494

**Comment by felicianotech** [comment]
This has been published.

**Comment by wildstarzw** [comment]
My CI build start falling from few hours ago, is it related to this change?
I am using
` - image: circleci/android:api-29`
And the error messages are ⬇️
> Task :app:ktlintAndroidTestSourceSetCheck FAILED
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at com.pinterest.ktlint.Main.loadJARs(Main.kt:725)
	at com.pinterest.ktlint.Main.main(Main.kt:306)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:ktlintAndroidTestSourceSetCheck'.
> Process 'command '/usr/local/openjdk-11/bin/java'' finished with non-zero exit value 1
