### ISSUE TITLE
Recent upgrade to java 11 for DockerFile image breaks android compilation

### ISSUE THREAD

**Issue by willlockwood** [circleci/circleci-images#504]
The JAXB APIs were removed from Java 11, but android compiles on 6/7/8, which includes them. On Java 11, we're missing JAXB from our classpaths, so android builds are breaking in our CI environments.

The change seems to have been introduced here: https://github.com/CircleCI-Public/circleci-dockerfiles/commit/18327f0bec24c640b6563ddb81967ee21de0e333 @felicianotech 

See the follow SO post for details about the interaction between the JAXB APIs and the various java versions: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

```
> Task :app:kaptDebugKotlin FAILED
...
e: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	at org.jetbrains.kotlin.cli.jvm.plugins.ServiceLoaderLite.loadImplementations(ServiceLoaderLite.kt:51)
...
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 43 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> Internal compiler error. See log for more details
```

I'm happy to provide more detail if possible, but for now I was mainly just hoping to get this issue up, so feel free to let me know what other information I can provide?

**Comment by felicianotech** [comment]
Please see the migrating section of this post: https://discuss.circleci.com/t/android-convenience-image-moving-to-java-v11-on-august-17th/36601

In short, you can pin to the last instead you were using.

**Comment by willlockwood** [comment]
Checking it out now. Thank you for letting me know!

**Comment by willlockwood** [comment]
And we have resolved this internally. Thank you! 

We found that this also worked, as a workaround, for anyone who would like to avoid pinning to the latest image: 

In our app's `build.gradle` file, added:
```
...
import org.gradle.util.VersionNumber

// Dependencies to be able to build with Java 9+
ext.java9Jdk9depsVersion = "1.0"
ext.java9JaxbCoreVersion = "2.3.0.1"
ext.java9JaxbApiVersion = "2.3.1"
ext.java9JaxbImplVersion = "2.3.2"
def javaMajorVersion = VersionNumber.parse(System.properties["java.version"]).major
if (javaMajorVersion >= 9) {
    allprojects {
        afterEvaluate {
            if (pluginManager.hasPlugin("kotlin-android")) {
                if (android.dataBinding.enabled) {
                    dependencies {
                        compileOnly "com.github.pengrad:jdk9-deps:$java9Jdk9depsVersion"
                        annotationProcessor "com.sun.xml.bind:jaxb-core:$java9JaxbCoreVersion"
                        annotationProcessor "javax.xml.bind:jaxb-api:$java9JaxbApiVersion"
                        annotationProcessor "com.sun.xml.bind:jaxb-impl:$java9JaxbImplVersion"
                    }
                }
                if (pluginManager.hasPlugin("kotlin-kapt")) {
                    dependencies {
                        kapt "com.sun.xml.bind:jaxb-core:$java9JaxbCoreVersion"
                        kapt "javax.xml.bind:jaxb-api:$java9JaxbApiVersion"
                        kapt "com.sun.xml.bind:jaxb-impl:$java9JaxbImplVersion"
                    }
                }
            }
        }
    }
}
```
