### ISSUE TITLE
DynamoDB image throws `java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter`

### ISSUE THREAD

**Issue by mt-kelvintaywl** [circleci/circleci-images#511]
Hi,

I tried running the latest dynamodb image (`circleci/dynamodb:latest`) on CircleCI as as well using the docker image locally, but encountered the following error when running the image and having a service interact with the DynamoDB

```
Aug 26, 2020 4:46:47 AM com.almworks.sqlite4java.Internal log
WARNING: [sqlite] SQLiteDBAccess$20@2f2c61b5: job exception
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$20.doWork(SQLiteDBAccess.java:2109)
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$20.doWork(SQLiteDBAccess.java:2010)
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.AmazonDynamoDBOfflineSQLiteJob.job(AmazonDynamoDBOfflineSQLiteJob.java:117)
	at com.almworks.sqlite4java.SQLiteJob.execute(SQLiteJob.java:372)
	at com.almworks.sqlite4java.SQLiteQueue.executeJob(SQLiteQueue.java:534)
	at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:667)
	at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
	at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
	at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Alternatively, AWS's official DynamoDB image `amazon/dynamodb-local` is running fine and I've temporarily switched out to that.

**Comment by mt-kelvintaywl** [comment]
What i am curious is, since today, the `circleci/dynamodb` image seems broken on that note.

I looked at the entrypoints of both images and they seem similar:

```sh
$ docker inspect amazon/dynamodb-local:latest | jq ".[0].Config"

{
  "Hostname": "",
  "Domainname": "",
  "User": "dynamodblocal",
  "AttachStdin": false,
  "AttachStdout": false,
  "AttachStderr": false,
  "ExposedPorts": {
    "8000/tcp": {}
  },
  "Tty": false,
  "OpenStdin": false,
  "StdinOnce": false,
  "Env": [
    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  ],
  "Cmd": [
    "-jar",
    "DynamoDBLocal.jar",
    "-inMemory"
  ],
  "Image": "sha256:c409007202cc3f0889559172ef3ee2651f89a1267e1c5ef038047140f65bb015",
  "Volumes": null,
  "WorkingDir": "/home/dynamodblocal",
  "Entrypoint": [
    "java"
  ],
  "OnBuild": null,
  "Labels": {
    "aws.java.sdk.version": "1.13.3"
  }
}
```

```sh
$ docker inspect circleci/dynamodb:latest | jq ".[0].Config"

{
  "Hostname": "",
  "Domainname": "",
  "User": "",
  "AttachStdin": false,
  "AttachStdout": false,
  "AttachStderr": false,
  "ExposedPorts": {
    "8000/tcp": {}
  },
  "Tty": false,
  "OpenStdin": false,
  "StdinOnce": false,
  "Env": [
    "PATH=/usr/java/openjdk-14/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "LANG=en_US.UTF-8",
    "JAVA_HOME=/usr/java/openjdk-14",
    "JAVA_VERSION=14.0.2"
  ],
  "Cmd": null,
  "Image": "sha256:2a4beac28173a041c02135777216f81b4822fc8884aa46935dacc25d9586a60c",
  "Volumes": null,
  "WorkingDir": "/opt/dynamodb",
  "Entrypoint": [
    "java",
    "-Xmx1G",
    "-jar",
    "DynamoDBLocal.jar"
  ],
  "OnBuild": null,
  "Labels": null
}
```

**Comment by felicianotech** [comment]
Thank you for reporting. Will take a look.

**Comment by felicianotech** [comment]
@mt-kelvintaywl Can you let me know which actual image you tried to use? It looks like the one you mentioned, `circleci/dynamodb:local` isn't an image.

**Comment by mt-kelvintaywl** [comment]
> @mt-kelvintaywl Can you let me know which actual image you tried to use? It looks like the one you mentioned, `circleci/dynamodb:local` isn't an image.

Hi @felicianotech, thank you for looking into this.

I was using the `circleci/dynamodb:latest` image.

**Comment by mt-kelvintaywl** [comment]
@felicianotech 

This is rather odd, as I am now unable to reproduce it locally nor is it happening on my CircleCI build. 
That's good news for me, ultimately 😅 

Looks like the latest build @ https://hub.docker.com/layers/circleci/dynamodb/latest/images/sha256-e4684e0b7f1248d3124cd9444d630b4f7047d616c48ac05eb555c0cd7d5a136c?context=explore seem to work fine for me now 👏 

Thank you so much, and I'll close this issue 🙇
